module.exports = function(craft){
	craft.pack()
		.name('standard')
		.add(require('./basic/canvas'))
		.add(require('./basic/chair1'))
		.add(require('./basic/cube'))	
		.add(require('./basic/pin'))
		.add(require('./basic/cross'))
		.add(require('./basic/table'))
		.add(require('./basic/text'))
		.add(require('./access/barchart'))
		.add(require('./access/braille'))
		.add(require('./access/piechart'))
		.add(require('./texture/grill'))
		.add(require('./texture/wave'))
}