module.exports = function(craft){
	craft.pack()
		.name('standard')
		.add(require('./basic/board'))
		.add(require('./basic/placeholder'))
		.add(require('./basic/chair1'))
		.add(require('./basic/cube'))	
		.add(require('./basic/pin'))
		.add(require('./basic/cross'))
		.add(require('./basic/desk'))
		.add(require('./basic/text'))
		.add(require('./basic/ring'))
		.add(require('./basic/flower'))
		.add(require('./basic/cup'))
		.add(require('./access/braille'))
		.add(require('./access/barchart'))		
		.add(require('./access/piechart'))
		.add(require('./texture/grill'))
		.add(require('./texture/wave'))

}
