module.exports = function(craft){
	craft.pack()
		.name('standard')
		.add(require('./basic/canvas'))	
		.add(require('./basic/pin'))
		.add(require('./basic/cross'))
		.add(require('./basic/table'))
		.add(require('./basic/text'))
		.add(require('./basic/ring'))
		.add(require('./basic/flower'))
		.add(require('./basic/button2'))
		.add(require('./basic/chair2'))
		.add(require('./basic/comb2'))
		.add(require('./basic/piano_keys'))
		.add(require('./basic/spiral'))
		.add(require('./basic/stairs'))
		.add(require('./basic/dice'))
		.add(require('./basic/cup'))
		.add(require('./access/barchart'))
		.add(require('./access/braille'))
		.add(require('./access/piechart'))
		.add(require('./texture/grill'))
		.add(require('./texture/wave'))

}
